POST http://localhost:5000/api/signup
Content-Type: application/json

{   
    "email": "david97molano@hotmail.com",
    "password": "elmolda2020",
    "name": "David",
    "lastname": "Molano",
    "rol": "Student"
}